
services:
  portfolio-website:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    container_name: portfolio-website-dev
    volumes:
      - ./src:/app/src:ro